# Generated by Django 6.0.2 on 2026-05-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_footerlinks_navlinks_platformsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(max_length=100)),
                ('secondary_color', models.CharField(max_length=100)),
                ('bg_color', models.CharField(max_length=100)),
            ],
        ),
    ]
