# Generated by Django 6.0.2 on 2026-05-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='name',
            field=models.CharField(default='Colors', max_length=255),
        ),
    ]
