# Generated by Django 6.0.2 on 2026-05-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_sitesettings_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsection',
            name='query_url',
        ),
        migrations.AddField(
            model_name='productsection',
            name='max_products',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='productsection',
            name='search_query',
            field=models.CharField(blank=True, help_text='e.g. category=Floral&gender=men', max_length=255, null=True),
        ),
    ]
