# Generated by Django 6.0.2 on 2026-05-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_productsection_query_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='banner_link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='homecategory',
            name='link',
            field=models.CharField(max_length=255),
        ),
    ]
