# Generated by Django 6.0.2 on 2026-05-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_heroslide_link_alter_homebanner_banner_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsection',
            name='card_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='productsection',
            name='container_width',
            field=models.CharField(choices=[('standard', 'Standard (1280px)'), ('wide', 'Wide (1400px)'), ('full', 'Full Width')], default='wide', max_length=10),
        ),
    ]
