# Generated by Django 6.0.2 on 2026-05-05 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_productsection_card_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero Carousel'), ('features', 'Features Bar'), ('products', 'Product Section'), ('categories', 'Editorial Categories'), ('banner', 'Promotional Banner'), ('reviews', 'Reviews Carousel'), ('faq', 'FAQ Section')], max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product_section', models.ForeignKey(blank=True, help_text='Select if type is Product Section', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.productsection')),
            ],
            options={
                'verbose_name': 'Homepage Section Order',
                'verbose_name_plural': 'Homepage Section Ordering',
                'ordering': ['display_order'],
            },
        ),
    ]
