# Generated by Django 6.0.2 on 2026-05-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_homepageorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="The title of the page (e.g., 'About Us')", max_length=200)),
                ('slug', models.SlugField(help_text="The URL slug (e.g., 'about-us')", max_length=200, unique=True)),
                ('content', models.TextField(help_text='The main content of the page. Supports HTML.')),
                ('meta_description', models.CharField(blank=True, help_text='Description for search engines.', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to show/hide the page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Static Page',
                'verbose_name_plural': 'Static Pages',
                'ordering': ['title'],
            },
        ),
    ]
