# Generated by Django 6.0.2 on 2026-05-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_staticpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_image', models.ImageField(blank=True, help_text='Featured image on the login page (Desktop only).', null=True, upload_to='auth/')),
                ('signup_image', models.ImageField(blank=True, help_text='Featured image on the signup page (Desktop only).', null=True, upload_to='auth/')),
                ('terms_link', models.CharField(blank=True, help_text='Full URL to the Terms of Service page.', max_length=255, null=True)),
                ('privacy_policy_link', models.CharField(blank=True, help_text='Full URL to the Privacy Policy page.', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Auth Page Settings',
                'verbose_name_plural': 'Auth Page Settings',
            },
        ),
    ]
