# Generated by Django 6.0.2 on 2026-05-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.PositiveIntegerField(help_text='Size in ml')),
            ],
            options={
                'ordering': ['value'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='base_notes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='heart_notes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_ml',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='top_notes',
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(related_name='products', to='products.size'),
        ),
    ]
