# Generated by Django 6.0.2 on 2026-05-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_size_remove_product_base_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='heart_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='top_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='size',
            name='value',
            field=models.PositiveIntegerField(choices=[(5, '5ml (Sample)'), (10, '10ml (Travel Size)'), (15, '15ml'), (30, '30ml'), (50, '50ml'), (75, '75ml'), (90, '90ml'), (100, '100ml'), (125, '125ml'), (150, '150ml'), (200, '200ml'), (250, '250ml')], default=100),
        ),
    ]
