# Generated by Django 6.0.2 on 2026-05-02 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_base_notes_product_heart_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_notes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='heart_notes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='top_notes',
        ),
    ]
