# Generated by Django 6.0.2 on 2026-05-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_base_notes_remove_product_heart_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='heart_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='top_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
