# Generated by Django 6.0.2 on 2026-05-02 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_base_notes_product_heart_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='name',
        ),
    ]
